# Generated by Django 4.1.7 on 2023-03-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
